<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>LRouxTech.Sample.Auth</RootNamespace>
        <UserSecretsId>4e35b34e-2cf8-458c-97fa-d59bc1511f6a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.8" />
        <PackageReference Include="Scalar.AspNetCore" Version="2.14.14" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\LRouxTech.Core.Auth\LRouxTech.Core.Auth.csproj" />
    </ItemGroup>

</Project>
