<Project Sdk="Aspire.AppHost.Sdk/13.4.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>2fc503fa-4f20-47e9-9b93-2cfec419f76a</UserSecretsId>
        <RootNamespace>LRouxTech.AppHost.Auth</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\LRouxTech.Sample.Auth\LRouxTech.Sample.Auth.csproj" />
    </ItemGroup>

</Project>
